@url = http://localhost:5071

POST {{url}}/register
Content-Type: application/json

{
    "Email": "testadmin@gmail.com",
    "Password": "@Admin00"
}

###

GET {{url}}/pingauth

###

POST {{url}}/addToCart
Content-Type: application/json
Cookie: .AspNetCore.Identity.Application=CfDJ8BimS0EU7TRBpLNIPGxxPNqaf7FzgMrQmhF52R50CHtnE9ULnVOjFbtV42ZLW7rXgFcnue7Z26_vs7qG0U3PkcsfpxIhnY0FMvy-0LbGjQlLG-Wl0ALvwe-WT6RskLxUFWfCgixACiVsRaoVGu3N_0SFcZeg7rk_XDCEWgLzKu-GU3pQR4Nm9KrBzvxbxa0muO3Di6ju4DOf3biz1f7lN8crrBMlR0hzKLFJDiUeMPsiowavwijuAZx1NYDiRw1A8WWQjdbIGcy2YSdjUpgtg9mwKYfmEg6u9B6564M0fsiLU-XetcCQ5e8oRBIdODRwj1dDZ-KZCN7VCqWcQ4INjUFygBeyEmDSPqZyGLN4wK5FNpDTEJYdT_YHsNQ7XsUJuYAQ_-B6pSB3Qx5ukYakQzSEOgZgKhflpRlbCH4CLZVbf0hqPoH9JUjkePPlc2OatDTyqGmktFW-At-XMUfFVOrPc77vf1c5UqZwX_NsGimXuecXy3pzGqMn-OEU5sumgb8Bevlm--W7dydJlonry7KUryfsqjj4jpfjPry16CgT-tx7_IJ0c2FbWpeuvNUhWbkvpP9iw7_RlwcstMgyLRvyVTPh8663hLoKYauCxF5jmIwImG6ypCjESkFP8fzTdUgJ0RpWjmBzyJGHvCDu6W3wRPu9qxLSnhFOYFtTQ6pZmYGbr4rkExP-gjey-HxBfwiou4ADHLuAX1pHVD8JsZJvG9UBAZEC6RRpflpNe43-

{
    "ProductId": 1,
    "ProductType": "Food",
    "Quantity": 1,
}

###

// FOOD ENDPOINTS
GET {{url}}/getAllFoodProducts

###

GET {{url}}/food/4

###

POST {{url}}/postFood
Content-Type: application/json

{
    "ImageUrl": "testPostFoodUrl",
    "Name": "testPostFoodName",
    "Description": "testPostFoodDesc",
    "Price": 2.30,
    "Rating": 3.7,
    "Category": "testPostFoodCategory",
    "Quantity": 1
}

###

PUT {{url}}/putFood/6
Content-Type: application/json

{
    "ImageUrl": "testPUTFoodUrl",
    "Name": "testPUTFoodName",
    "Description": "testPUTFoodDesc",
    "Price": 1.23,
    "Rating": 1.2,
    "Category": "testPUTFoodCategory",
    "Quantity": 2
}
###

DELETE {{url}}/deleteFood/6

###

// DRINK ENDPOINTS
GET {{url}}/getAllDrinkProducts

###

GET {{url}}/drink/1

###

POST {{url}}/postDrink
Content-Type: application/json

{
    "ImageUrl": "testPostDrinkUrl",
    "Name": "testPostDrinkName",
    "Description": "testPostDrinkDesc",
    "Price": 1.50,
    "Rating": 4.3,
    "Category": "testPostDrinkCategory",
    "Quantity": 1
}

###

PUT {{url}}/putDrink/3
Content-Type: application/json

{
    "ImageUrl": "testPUTDrinkUrl",
    "Name": "testPUTDrinkName",
    "Description": "testPUTDrinkDesc",
    "Price": 13.23,
    "Rating": 3.8,
    "Category": "testPUTDrinkCategory",
    "Quantity": 3
}

###

DELETE {{url}}/deleteDrink/3